Rerequest check suite

diff --git a/.github/workflows/retry.yml b/.github/workflows/retry.yml
--- a/.github/workflows/retry.yml
+++ b/.github/workflows/retry.yml
@@ -5,30 +5,30 @@ on:
   workflow_dispatch:
 
 jobs:
-  randomly-failing-job:
-    runs-on: ubuntu-latest
-    outputs:
-      job_id_url: ${{ steps.jobs.outputs.html_url }}
-    steps:
-      - name: Get Current Job Log URL
-        uses: Tiryoh/gha-jobid-action@v0
-        id: jobs
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          job_name: randomly-failing-job
+  # randomly-failing-job:
+  #   runs-on: ubuntu-latest
+  #   outputs:
+  #     job_id_url: ${{ steps.jobs.outputs.html_url }}
+  #   steps:
+  #     - name: Get Current Job Log URL
+  #       uses: Tiryoh/gha-jobid-action@v0
+  #       id: jobs
+  #       with:
+  #         github_token: ${{ secrets.GITHUB_TOKEN }}
+  #         job_name: randomly-failing-job
 
-      # - name: Output Current Job Log URL
-      #   run: echo "job-id=${{ steps.jobs.outputs.html_url }}
+  #     # - name: Output Current Job Log URL
+  #     #   run: echo "job-id=${{ steps.jobs.outputs.html_url }}
 
-      - name: Step that fails randomly
-        run: |
-          exit $((RANDOM % 2))
-          echo $?
+  #     - name: Step that fails randomly
+  #       run: |
+  #         exit $((RANDOM % 2))
+  #         echo $?
 
   retry-job:
     runs-on: ubuntu-latest
-    if: ${{ failure() }} # exeutes job if ancestor job have failed
-    needs: randomly-failing-job
+    # if: ${{ failure() }} # exeutes job if ancestor job have failed
+    # needs: randomly-failing-job
     steps:
       # - name: Extract workflow id from job URL
       #   id: get-workflow-id
@@ -68,11 +68,21 @@ jobs:
       #       -H "X-GitHub-Api-Version: 2022-11-28" \
       #       https://api.github.com/repos/michalinacienciala/experimental/actions/jobs/$(echo ${{needs.randomly-failing-job.outputs.job_id_url}} | sed -n "s/^.*jobs\/\([0-9]*\)/\1/p")/rerun
         
-      - name: Rerun failing `randomly-failing-job` job
+      # - name: Rerun failing `randomly-failing-job` job
+      #   run: |
+      #     curl \
+      #       -X POST \
+      #       -H "Accept: application/vnd.github+json" \
+      #       -H "Authorization: Bearer ${{ secrets.RERUN_TOKEN }}"\
+      #       -H "X-GitHub-Api-Version: 2022-11-28" \
+      #       https://api.github.com/repos/michalinacienciala/experimental/actions/jobs/randomly-failing-job/rerun
+
+      - name: Rerequest check suite
         run: |
           curl \
             -X POST \
             -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer ${{ secrets.RERUN_TOKEN }}"\
             -H "X-GitHub-Api-Version: 2022-11-28" \
-            https://api.github.com/repos/michalinacienciala/experimental/actions/jobs/randomly-failing-job/rerun
+            -H referer: https://github.com/michalinacienciala/experimental/actions/runs/4076347788/jobs/7024266714 \
+            https://api.github.com/repos/michalinacienciala/experimental/actions/runs/4076347788/rerequest_check_suite
